/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOrchestratorRouteImport } from './routes/_app.orchestrator'
import { Route as AppInstagramRouteImport } from './routes/_app.instagram'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAhoRouteImport } from './routes/_app.aho'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrchestratorRoute = AppOrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => AppRoute,
} as any)
const AppInstagramRoute = AppInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAhoRoute = AppAhoRouteImport.update({
  id: '/aho',
  path: '/aho',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aho': typeof AppAhoRoute
  '/dashboard': typeof AppDashboardRoute
  '/hr': typeof AppHrRoute
  '/instagram': typeof AppInstagramRoute
  '/orchestrator': typeof AppOrchestratorRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aho': typeof AppAhoRoute
  '/dashboard': typeof AppDashboardRoute
  '/hr': typeof AppHrRoute
  '/instagram': typeof AppInstagramRoute
  '/orchestrator': typeof AppOrchestratorRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/aho': typeof AppAhoRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/instagram': typeof AppInstagramRoute
  '/_app/orchestrator': typeof AppOrchestratorRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aho'
    | '/dashboard'
    | '/hr'
    | '/instagram'
    | '/orchestrator'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aho'
    | '/dashboard'
    | '/hr'
    | '/instagram'
    | '/orchestrator'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/aho'
    | '/_app/dashboard'
    | '/_app/hr'
    | '/_app/instagram'
    | '/_app/orchestrator'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orchestrator': {
      id: '/_app/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof AppOrchestratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instagram': {
      id: '/_app/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AppInstagramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aho': {
      id: '/_app/aho'
      path: '/aho'
      fullPath: '/aho'
      preLoaderRoute: typeof AppAhoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAhoRoute: typeof AppAhoRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHrRoute: typeof AppHrRoute
  AppInstagramRoute: typeof AppInstagramRoute
  AppOrchestratorRoute: typeof AppOrchestratorRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAhoRoute: AppAhoRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHrRoute: AppHrRoute,
  AppInstagramRoute: AppInstagramRoute,
  AppOrchestratorRoute: AppOrchestratorRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
